import { Achievement } from '@/types/achievements';

export const tutorialAchievements: Achievement[] = [
  {
    id: 'tutorial-master',
    title: 'Tutorial Master',
    description: 'Complete all main dashboard tutorials',
    icon: 'trophy',
    category: 'tutorial',
    requiredSteps: [
      'dashboard-overview',
      'analytics-deep-dive',
      'projects-management',
      'settings-configuration',
    ],
    reward: {
      type: 'badge',
      value: 'tutorial-master',
    },
  },
  {
    id: 'analytics-expert',
    title: 'Analytics Expert',
    description: 'Master the analytics dashboard and all its features',
    icon: 'barChart',
    category: 'mastery',
    requiredSteps: [
      'analytics-overview',
      'metrics-overview',
      'performance-charts',
      'team-metrics',
      'custom-reports',
    ],
    reward: {
      type: 'feature',
      value: 'advanced-analytics',
    },
  },
  {
    id: 'project-pioneer',
    title: 'Project Pioneer',
    description: 'Create and manage your first complete project',
    icon: 'folder',
    category: 'usage',
    requiredSteps: [
      'project-creation',
      'project-setup',
      'team-assignment',
      'milestone-creation',
    ],
    reward: {
      type: 'feature',
      value: 'project-templates',
    },
  },
  {
    id: 'context-master',
    title: 'Context Master',
    description: 'Master the AI context gathering system',
    icon: 'brain',
    category: 'mastery',
    requiredSteps: [
      'context-creation',
      'ai-assistance',
      'context-refinement',
      'context-linking',
    ],
    reward: {
      type: 'feature',
      value: 'advanced-ai',
    },
  },
  {
    id: 'team-leader',
    title: 'Team Leader',
    description: 'Successfully manage a team and complete a project',
    icon: 'users',
    category: 'usage',
    requiredSteps: [
      'team-creation',
      'role-assignment',
      'task-delegation',
      'project-completion',
    ],
    reward: {
      type: 'feature',
      value: 'team-analytics',
    },
  },
  {
    id: 'efficiency-expert',
    title: 'Efficiency Expert',
    description: 'Complete tasks ahead of schedule consistently',
    icon: 'alert',
    category: 'mastery',
    requiredSteps: [
      'task-optimization',
      'time-management',
      'resource-allocation',
      'workflow-improvement',
    ],
    reward: {
      type: 'theme',
      value: 'pro-dark',
    },
  },
  {
    id: 'integration-master',
    title: 'Integration Master',
    description: 'Successfully connect and use external integrations',
    icon: 'plug',
    category: 'usage',
    requiredSteps: [
      'integration-setup',
      'data-sync',
      'workflow-automation',
      'api-usage',
    ],
    reward: {
      type: 'feature',
      value: 'custom-integrations',
    },
  },
  {
    id: 'documentation-guru',
    title: 'Documentation Guru',
    description: 'Create comprehensive project documentation',
    icon: 'eye',
    category: 'mastery',
    requiredSteps: [
      'docs-creation',
      'template-usage',
      'knowledge-base',
      'docs-sharing',
    ],
    reward: {
      type: 'feature',
      value: 'advanced-docs',
    },
  },
  {
    id: 'reporting-master',
    title: 'Reporting Master',
    description: 'Create and customize advanced reports',
    icon: 'barChart',
    category: 'mastery',
    requiredSteps: [
      'report-creation',
      'data-visualization',
      'custom-metrics',
      'report-automation',
    ],
    reward: {
      type: 'feature',
      value: 'advanced-reporting',
    },
  },
  {
    id: 'ai-innovator',
    title: 'AI Innovator',
    description: 'Master AI-powered features and automation',
    icon: 'sparkles',
    category: 'mastery',
    requiredSteps: [
      'ai-context',
      'ai-suggestions',
      'workflow-automation',
      'predictive-analytics',
    ],
    reward: {
      type: 'feature',
      value: 'ai-automation',
    },
  },
  {
    id: 'collaboration-champion',
    title: 'Collaboration Champion',
    description: 'Excel at team collaboration and communication',
    icon: 'users',
    category: 'usage',
    requiredSteps: [
      'team-chat',
      'file-sharing',
      'feedback-loops',
      'status-updates',
    ],
    reward: {
      type: 'feature',
      value: 'advanced-collaboration',
    },
  },
  {
    id: 'customization-expert',
    title: 'Customization Expert',
    description: 'Master system customization and personalization',
    icon: 'settings',
    category: 'mastery',
    requiredSteps: [
      'theme-customization',
      'workflow-templates',
      'dashboard-layouts',
      'notification-rules',
    ],
    reward: {
      type: 'theme',
      value: 'custom-themes',
    },
  },
];
