import { TutorialSection } from '@/types/tutorial';

export const tutorialData: TutorialSection[] = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    description: 'Learn the basics of Spec Tree',
    completed: false,
    steps: [
      {
        id: 'welcome',
        title: 'Welcome to Spec Tree',
        description:
          'Get started with the basics of creating and managing project requirements.',
        target: '.dashboard-header',
        placement: 'bottom',
        order: 1,
        section: 'getting-started',
      },
      {
        id: 'navigation',
        title: 'Navigation Overview',
        description:
          'Learn how to navigate through different sections of the application.',
        target: '.sidebar-nav',
        placement: 'right',
        order: 2,
        section: 'getting-started',
      },
      {
        id: 'projects-overview',
        title: 'Projects Overview',
        description:
          'View and manage your active projects from one central location.',
        target: '.project-overview',
        placement: 'bottom',
        order: 3,
        section: 'getting-started',
      },
      {
        id: 'analytics-intro',
        title: 'Analytics Dashboard',
        description:
          'Get insights into your project performance and team productivity.',
        target: '.analytics-metrics',
        placement: 'left',
        order: 4,
        section: 'getting-started',
      },
      {
        id: 'achievements-intro',
        title: 'Achievements System',
        description:
          'Track your progress and unlock rewards as you master Spec Tree.',
        target: '.achievements-display',
        placement: 'right',
        order: 5,
        section: 'getting-started',
      },
    ],
  },
  {
    id: 'ai-context',
    title: 'AI Context Creation',
    description: 'Master the AI-powered context gathering system',
    completed: false,
    steps: [
      {
        id: 'context-overview',
        title: 'Context Overview',
        description:
          'Learn how AI helps gather and refine project requirements.',
        target: '.context-overview',
        placement: 'bottom',
        order: 1,
        section: 'ai-context',
      },
      {
        id: 'question-generation',
        title: 'Question Generation',
        description:
          'See how AI generates relevant questions based on your project type.',
        target: '.question-generator',
        placement: 'right',
        order: 2,
        section: 'ai-context',
      },
      {
        id: 'context-refinement',
        title: 'Context Refinement',
        description:
          'Learn to refine and improve context using AI suggestions.',
        target: '.context-editor',
        placement: 'left',
        order: 3,
        section: 'ai-context',
      },
      {
        id: 'context-propagation',
        title: 'Context Propagation',
        description:
          'Understand how context flows through your project hierarchy.',
        target: '.context-flow',
        placement: 'right',
        order: 4,
        section: 'ai-context',
      },
    ],
  },
  {
    id: 'analytics-deep-dive',
    title: 'Analytics & Reporting',
    description: 'Master the analytics dashboard and reporting features',
    completed: false,
    steps: [
      {
        id: 'analytics-overview',
        title: 'Analytics Dashboard',
        description: 'Get a comprehensive view of your analytics dashboard.',
        target: '.analytics-header',
        placement: 'bottom',
        order: 1,
        section: 'analytics-deep-dive',
      },
      {
        id: 'metrics-overview',
        title: 'Key Performance Metrics',
        description:
          'Learn about important metrics tracking task completion and team performance.',
        target: '.metrics-cards',
        placement: 'bottom',
        order: 2,
        section: 'analytics-deep-dive',
      },
      {
        id: 'performance-charts',
        title: 'Performance Charts',
        description: 'Analyze trends and patterns in your project data.',
        target: '.performance-charts',
        placement: 'right',
        order: 3,
        section: 'analytics-deep-dive',
      },
      {
        id: 'custom-reports',
        title: 'Custom Reports',
        description: 'Create and customize reports for your specific needs.',
        target: '.custom-reports',
        placement: 'left',
        order: 4,
        section: 'analytics-deep-dive',
      },
      {
        id: 'export-options',
        title: 'Export & Share',
        description:
          'Learn how to export and share your analytics with stakeholders.',
        target: '.export-controls',
        placement: 'top',
        order: 5,
        section: 'analytics-deep-dive',
      },
    ],
  },
  {
    id: 'project-management',
    title: 'Project Management',
    description: 'Learn to effectively manage your projects',
    completed: false,
    steps: [
      {
        id: 'create-project',
        title: 'Creating Projects',
        description: 'Start a new project using AI-powered templates.',
        target: '.create-project-button',
        placement: 'right',
        order: 1,
        section: 'project-management',
      },
      {
        id: 'work-hierarchy',
        title: 'Work Item Hierarchy',
        description:
          'Understand how Epics, Features, and Stories relate to each other.',
        target: '.work-hierarchy',
        placement: 'left',
        order: 2,
        section: 'project-management',
      },
      {
        id: 'team-collaboration',
        title: 'Team Collaboration',
        description: 'Learn how to collaborate effectively with your team.',
        target: '.team-section',
        placement: 'right',
        order: 3,
        section: 'project-management',
      },
      {
        id: 'tracking-progress',
        title: 'Progress Tracking',
        description: 'Monitor project progress and track deliverables.',
        target: '.progress-tracking',
        placement: 'bottom',
        order: 4,
        section: 'project-management',
      },
    ],
  },
  {
    id: 'advanced-features',
    title: 'Advanced Features',
    description: 'Explore advanced features and customization options',
    completed: false,
    steps: [
      {
        id: 'custom-templates',
        title: 'Custom Templates',
        description: 'Create and manage custom project templates.',
        target: '.template-manager',
        placement: 'right',
        order: 1,
        section: 'advanced-features',
      },
      {
        id: 'integrations',
        title: 'External Integrations',
        description: 'Connect Spec Tree with your favorite tools.',
        target: '.integrations-panel',
        placement: 'left',
        order: 2,
        section: 'advanced-features',
      },
      {
        id: 'automation',
        title: 'Workflow Automation',
        description: 'Set up automated workflows and notifications.',
        target: '.automation-settings',
        placement: 'bottom',
        order: 3,
        section: 'advanced-features',
      },
      {
        id: 'api-access',
        title: 'API Access',
        description: 'Learn how to access and use the Spec Tree API.',
        target: '.api-documentation',
        placement: 'right',
        order: 4,
        section: 'advanced-features',
      },
    ],
  },
];
