import type { Metadata } from 'next';
import './globals.css';
import { FontProvider } from '@/components/FontManager';
import { SidebarProvider } from '@/components/ui/sidebar';
import StyleWrapper from './StyleWrapper';
import StoreProvider from './StoreProvider';
import { MainNav } from '@/components/layout/MainNav';
import { Footer } from '@/components/layout/Footer';
import { Toaster } from '@/components/ui/toaster';
import { Layout } from '@/components/auth/Layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <FontProvider>
          <StoreProvider>
            <SidebarProvider>
              <StyleWrapper>
                <div className="relative flex min-h-screen flex-col">
                  <MainNav />
                  <Layout>
                    <main className="flex-1">{children}</main>
                  </Layout>
                  <Footer />
                </div>
                <Toaster />
              </StyleWrapper>
            </SidebarProvider>
          </StoreProvider>
        </FontProvider>
      </body>
    </html>
  );
}
