/**
 * Demo data for SpecTree demo mode
 * Contains sample spec trees showcasing the application's full functionality
 */

import {
  EpicType,
  FeatureType,
  UserStoryType,
  TaskType,
  App,
  SowState,
} from '@/components/spec-tree/lib/types/work-items';

// Sample Apps for Demo
export const demoApps: App[] = [
  {
    id: 'demo-app-ecommerce',
    name: 'E-Commerce Platform',
    documentId: 'demo-app-ecommerce',
    globalInformation: 'A modern e-commerce platform with AI-powered product recommendations, seamless checkout, and real-time inventory management.',
    applicationInformation: 'E-Commerce Platform - Full-stack web application built with Next.js, Node.js, and PostgreSQL.',
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'demo-app-taskmanager',
    name: 'Task Management System',
    documentId: 'demo-app-taskmanager',
    globalInformation: 'A collaborative task management system for teams with real-time updates, sprint planning, and performance analytics.',
    applicationInformation: 'Task Management System - Agile project management tool with Kanban boards and Gantt charts.',
    createdAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'demo-app-healthcare',
    name: 'Healthcare Portal',
    documentId: 'demo-app-healthcare',
    globalInformation: 'A secure patient portal for healthcare providers with appointment scheduling, medical records, and telehealth capabilities.',
    applicationInformation: 'Healthcare Portal - HIPAA-compliant patient management system.',
    createdAt: '2026-01-05T08:00:00Z',
  },
];

// E-Commerce Platform Demo Data
export const ecommerceEpics: Record<string, EpicType> = {
  'epic-1': {
    id: 'epic-1',
    documentId: 'epic-1',
    parentAppId: 'demo-app-ecommerce',
    title: 'User Authentication & Profile Management',
    description: 'Implement a secure authentication system with user profile management, social login options, and account settings.',
    goal: 'Enable users to securely access their accounts with multiple authentication methods and manage their personal information.',
    successCriteria: 'Users can register, login, and manage their profiles with 99.9% uptime and sub-200ms response times.',
    dependencies: 'Backend API, Database infrastructure, OAuth providers',
    timeline: '4 weeks',
    resources: '2 Full-stack developers, 1 Security specialist',
    risksAndMitigation: [
      {
        resolve: [{ text: 'Security vulnerabilities - Conduct security audit and penetration testing' }],
        own: [{ text: 'User data privacy - Implement GDPR compliance measures' }],
        accept: [{ text: 'Social login provider downtime - Provide email fallback option' }],
        mitigate: [{ text: 'Password complexity issues - Implement password strength meter and guidelines' }],
      },
    ],
    featureIds: ['feature-1', 'feature-2', 'feature-3'],
    notes: 'Priority: High. This epic is foundational for the entire application.',
    contextualQuestions: [],
  },
  'epic-2': {
    id: 'epic-2',
    documentId: 'epic-2',
    parentAppId: 'demo-app-ecommerce',
    title: 'Product Catalog & Search',
    description: 'Build a comprehensive product catalog with advanced search, filtering, and AI-powered recommendations.',
    goal: 'Provide users with an intuitive way to discover and find products efficiently.',
    successCriteria: 'Search results return in under 100ms with 95% relevance accuracy.',
    dependencies: 'Product database, Elasticsearch, ML recommendation engine',
    timeline: '6 weeks',
    resources: '3 Full-stack developers, 1 ML engineer',
    risksAndMitigation: [
      {
        resolve: [{ text: 'Search performance - Implement caching and query optimization' }],
        own: [{ text: 'Product data quality - Establish data validation pipelines' }],
        accept: [{ text: 'ML model accuracy limitations - Continuous model improvement' }],
        mitigate: [{ text: 'Large catalog scalability - Use pagination and lazy loading' }],
      },
    ],
    featureIds: ['feature-4', 'feature-5'],
    notes: 'Core feature for user engagement and conversion.',
    contextualQuestions: [],
  },
  'epic-3': {
    id: 'epic-3',
    documentId: 'epic-3',
    parentAppId: 'demo-app-ecommerce',
    title: 'Shopping Cart & Checkout',
    description: 'Implement a seamless shopping cart experience with multiple payment options and order tracking.',
    goal: 'Maximize conversion rates with a frictionless checkout process.',
    successCriteria: 'Cart abandonment rate below 20%, checkout completion in under 2 minutes.',
    dependencies: 'Payment gateway integrations, Inventory system, Order management',
    timeline: '5 weeks',
    resources: '2 Full-stack developers, 1 Payment integration specialist',
    risksAndMitigation: [
      {
        resolve: [{ text: 'Payment failures - Implement retry logic and multiple payment fallbacks' }],
        own: [{ text: 'PCI compliance - Use tokenization and certified payment processors' }],
        accept: [{ text: 'Currency conversion fluctuations - Show estimated amounts with disclaimers' }],
        mitigate: [{ text: 'Cart sync issues - Implement real-time cart synchronization' }],
      },
    ],
    featureIds: ['feature-6', 'feature-7'],
    notes: 'Critical revenue path - needs extensive testing.',
    contextualQuestions: [],
  },
};

export const ecommerceFeatures: Record<string, FeatureType> = {
  'feature-1': {
    id: 'feature-1',
    documentId: 'feature-1',
    parentEpicId: 'epic-1',
    title: 'Email/Password Registration',
    description: 'Allow users to create accounts using email and password with email verification.',
    details: 'Implement secure password hashing, email verification flow, and password recovery.',
    dependencies: 'Email service, User database',
    acceptanceCriteria: [
      { text: 'Users can register with valid email and strong password' },
      { text: 'Email verification is sent within 30 seconds' },
      { text: 'Password recovery flow works within 5 minutes' },
      { text: 'All passwords are hashed with bcrypt' },
    ],
    userStoryIds: ['story-1', 'story-2'],
    notes: 'Follow OWASP security guidelines',
    priority: 'High',
    effort: 'Medium',
    contextualQuestions: [],
  },
  'feature-2': {
    id: 'feature-2',
    documentId: 'feature-2',
    parentEpicId: 'epic-1',
    title: 'Social Login Integration',
    description: 'Enable users to sign in using Google, Facebook, and Apple accounts.',
    details: 'Implement OAuth 2.0 flows for each provider with account linking capabilities.',
    dependencies: 'OAuth providers, Account linking logic',
    acceptanceCriteria: [
      { text: 'Users can sign in with Google account' },
      { text: 'Users can sign in with Facebook account' },
      { text: 'Users can sign in with Apple account' },
      { text: 'Accounts can be linked to existing email accounts' },
    ],
    userStoryIds: ['story-3'],
    notes: 'Consider rate limiting for OAuth endpoints',
    priority: 'Medium',
    effort: 'Medium',
    contextualQuestions: [],
  },
  'feature-3': {
    id: 'feature-3',
    documentId: 'feature-3',
    parentEpicId: 'epic-1',
    title: 'User Profile Management',
    description: 'Allow users to view and edit their profile information, addresses, and preferences.',
    details: 'Create profile dashboard with editable fields, address management, and notification preferences.',
    dependencies: 'User database, File storage for avatars',
    acceptanceCriteria: [
      { text: 'Users can update personal information' },
      { text: 'Users can manage multiple shipping addresses' },
      { text: 'Users can set notification preferences' },
      { text: 'Profile changes are reflected immediately' },
    ],
    userStoryIds: ['story-4', 'story-5'],
    notes: 'Include profile completeness indicator',
    priority: 'Medium',
    effort: 'Low',
    contextualQuestions: [],
  },
  'feature-4': {
    id: 'feature-4',
    documentId: 'feature-4',
    parentEpicId: 'epic-2',
    title: 'Product Search & Filtering',
    description: 'Implement full-text search with category, price, and attribute filtering.',
    details: 'Use Elasticsearch for fast search with faceted navigation and autocomplete.',
    dependencies: 'Elasticsearch, Product catalog',
    acceptanceCriteria: [
      { text: 'Search returns results in under 100ms' },
      { text: 'Filters can be combined without page reload' },
      { text: 'Search suggestions appear after 2 characters' },
      { text: 'Results can be sorted by relevance, price, and ratings' },
    ],
    userStoryIds: ['story-6', 'story-7'],
    notes: 'Implement search analytics for improvement',
    priority: 'High',
    effort: 'High',
    contextualQuestions: [],
  },
  'feature-5': {
    id: 'feature-5',
    documentId: 'feature-5',
    parentEpicId: 'epic-2',
    title: 'AI Product Recommendations',
    description: 'Provide personalized product recommendations based on browsing history and preferences.',
    details: 'Implement collaborative filtering and content-based recommendation algorithms.',
    dependencies: 'ML model, User behavior tracking, Product catalog',
    acceptanceCriteria: [
      { text: 'Recommendations update in real-time based on user actions' },
      { text: 'Similar products shown on product detail pages' },
      { text: 'Personalized homepage recommendations for logged-in users' },
      { text: 'Recommendation click-through rate above 5%' },
    ],
    userStoryIds: ['story-8'],
    notes: 'Start with rule-based recommendations, then ML',
    priority: 'Medium',
    effort: 'High',
    contextualQuestions: [],
  },
  'feature-6': {
    id: 'feature-6',
    documentId: 'feature-6',
    parentEpicId: 'epic-3',
    title: 'Shopping Cart',
    description: 'Implement a persistent shopping cart with quantity management and price calculations.',
    details: 'Cart persists across sessions, handles inventory checks, and calculates totals with taxes and discounts.',
    dependencies: 'Product catalog, Pricing engine, Inventory system',
    acceptanceCriteria: [
      { text: 'Cart persists across browser sessions' },
      { text: 'Real-time inventory validation' },
      { text: 'Automatic tax and discount calculations' },
      { text: 'Cart syncs across devices for logged-in users' },
    ],
    userStoryIds: ['story-9', 'story-10'],
    notes: 'Implement cart recovery emails',
    priority: 'High',
    effort: 'Medium',
    contextualQuestions: [],
  },
  'feature-7': {
    id: 'feature-7',
    documentId: 'feature-7',
    parentEpicId: 'epic-3',
    title: 'Checkout & Payment Processing',
    description: 'Secure checkout flow with multiple payment options and order confirmation.',
    details: 'Integrate Stripe, PayPal, and Apple Pay with 3D Secure support.',
    dependencies: 'Payment gateways, Order management, Email service',
    acceptanceCriteria: [
      { text: 'Support credit cards, PayPal, and digital wallets' },
      { text: 'Implement 3D Secure for card payments' },
      { text: 'Order confirmation email sent within 1 minute' },
      { text: 'Failed payments show clear error messages' },
    ],
    userStoryIds: ['story-11', 'story-12'],
    notes: 'PCI compliance required - use Stripe Elements',
    priority: 'High',
    effort: 'High',
    contextualQuestions: [],
  },
};

export const ecommerceUserStories: Record<string, UserStoryType> = {
  'story-1': {
    id: 'story-1',
    documentId: 'story-1',
    parentFeatureId: 'feature-1',
    title: 'User Registration',
    role: 'new visitor',
    action: 'create an account with my email and password',
    goal: 'so that I can save my preferences and order history',
    points: '5',
    acceptanceCriteria: [
      { text: 'Email format is validated on input' },
      { text: 'Password strength indicator is shown' },
      { text: 'Terms and conditions acceptance is required' },
      { text: 'Success message shown after registration' },
    ],
    notes: 'Include CAPTCHA for bot prevention',
    taskIds: ['task-1', 'task-2', 'task-3'],
    developmentOrder: 1,
    dependentUserStoryIds: [],
    contextualQuestions: [],
  },
  'story-2': {
    id: 'story-2',
    documentId: 'story-2',
    parentFeatureId: 'feature-1',
    title: 'Email Verification',
    role: 'registered user',
    action: 'verify my email address through a verification link',
    goal: 'so that I can confirm my identity and access all features',
    points: '3',
    acceptanceCriteria: [
      { text: 'Verification email is sent within 30 seconds' },
      { text: 'Link expires after 24 hours' },
      { text: 'Resend verification option available' },
      { text: 'Account is activated upon successful verification' },
    ],
    notes: 'Email template should be mobile-friendly',
    taskIds: ['task-4', 'task-5'],
    developmentOrder: 2,
    dependentUserStoryIds: ['story-1'],
    contextualQuestions: [],
  },
  'story-3': {
    id: 'story-3',
    documentId: 'story-3',
    parentFeatureId: 'feature-2',
    title: 'Google Sign-In',
    role: 'user',
    action: 'sign in using my Google account',
    goal: 'so that I can quickly access the platform without creating a new password',
    points: '5',
    acceptanceCriteria: [
      { text: 'Google sign-in button is prominently displayed' },
      { text: 'User is redirected to Google OAuth consent screen' },
      { text: 'Account is created automatically for first-time users' },
      { text: 'Existing accounts can be linked to Google' },
    ],
    notes: 'Handle account already exists edge case',
    taskIds: ['task-6', 'task-7'],
    developmentOrder: 1,
    dependentUserStoryIds: [],
    contextualQuestions: [],
  },
  'story-4': {
    id: 'story-4',
    documentId: 'story-4',
    parentFeatureId: 'feature-3',
    title: 'Profile Information Update',
    role: 'logged-in user',
    action: 'update my personal information',
    goal: 'so that my account reflects my current details',
    points: '3',
    acceptanceCriteria: [
      { text: 'User can edit name, phone number, and avatar' },
      { text: 'Changes are saved automatically or with explicit save' },
      { text: 'Validation errors are shown inline' },
      { text: 'Success confirmation is displayed' },
    ],
    notes: 'Support image upload for avatar',
    taskIds: ['task-8'],
    developmentOrder: 1,
    dependentUserStoryIds: [],
    contextualQuestions: [],
  },
  'story-5': {
    id: 'story-5',
    documentId: 'story-5',
    parentFeatureId: 'feature-3',
    title: 'Address Management',
    role: 'logged-in user',
    action: 'manage multiple shipping addresses',
    goal: 'so that I can ship orders to different locations',
    points: '5',
    acceptanceCriteria: [
      { text: 'User can add up to 5 addresses' },
      { text: 'Default address can be set' },
      { text: 'Address validation is performed' },
      { text: 'Addresses can be edited and deleted' },
    ],
    notes: 'Integrate with address autocomplete API',
    taskIds: ['task-9', 'task-10'],
    developmentOrder: 2,
    dependentUserStoryIds: ['story-4'],
    contextualQuestions: [],
  },
  'story-6': {
    id: 'story-6',
    documentId: 'story-6',
    parentFeatureId: 'feature-4',
    title: 'Product Search',
    role: 'shopper',
    action: 'search for products using keywords',
    goal: 'so that I can quickly find what I am looking for',
    points: '8',
    acceptanceCriteria: [
      { text: 'Search bar is accessible from all pages' },
      { text: 'Results appear as user types (autocomplete)' },
      { text: 'Relevant results are shown first' },
      { text: 'Search history is saved for logged-in users' },
    ],
    notes: 'Implement fuzzy matching for typos',
    taskIds: ['task-11', 'task-12', 'task-13'],
    developmentOrder: 1,
    dependentUserStoryIds: [],
    contextualQuestions: [],
  },
  'story-7': {
    id: 'story-7',
    documentId: 'story-7',
    parentFeatureId: 'feature-4',
    title: 'Product Filtering',
    role: 'shopper',
    action: 'filter products by category, price, and attributes',
    goal: 'so that I can narrow down my search results',
    points: '8',
    acceptanceCriteria: [
      { text: 'Filters update results without page reload' },
      { text: 'Multiple filters can be combined' },
      { text: 'Active filters are clearly displayed' },
      { text: 'Filter counts show available options' },
    ],
    notes: 'Consider mobile-friendly filter panel',
    taskIds: ['task-14', 'task-15'],
    developmentOrder: 2,
    dependentUserStoryIds: ['story-6'],
    contextualQuestions: [],
  },
  'story-8': {
    id: 'story-8',
    documentId: 'story-8',
    parentFeatureId: 'feature-5',
    title: 'Product Recommendations',
    role: 'shopper',
    action: 'see personalized product recommendations',
    goal: 'so that I can discover products relevant to my interests',
    points: '13',
    acceptanceCriteria: [
      { text: 'Recommendations shown on homepage' },
      { text: 'Similar products shown on product pages' },
      { text: 'Recommendations based on browsing history' },
      { text: 'Users can dismiss irrelevant recommendations' },
    ],
    notes: 'A/B test recommendation algorithms',
    taskIds: ['task-16', 'task-17', 'task-18'],
    developmentOrder: 1,
    dependentUserStoryIds: [],
    contextualQuestions: [],
  },
  'story-9': {
    id: 'story-9',
    documentId: 'story-9',
    parentFeatureId: 'feature-6',
    title: 'Add to Cart',
    role: 'shopper',
    action: 'add products to my shopping cart',
    goal: 'so that I can purchase multiple items together',
    points: '5',
    acceptanceCriteria: [
      { text: 'Add to cart button on product pages and listings' },
      { text: 'Quantity selector available' },
      { text: 'Cart icon updates with item count' },
      { text: 'Success notification shown' },
    ],
    notes: 'Handle out-of-stock items gracefully',
    taskIds: ['task-19', 'task-20'],
    developmentOrder: 1,
    dependentUserStoryIds: [],
    contextualQuestions: [],
  },
  'story-10': {
    id: 'story-10',
    documentId: 'story-10',
    parentFeatureId: 'feature-6',
    title: 'Cart Management',
    role: 'shopper',
    action: 'view and manage my shopping cart',
    goal: 'so that I can review my selections before checkout',
    points: '5',
    acceptanceCriteria: [
      { text: 'Cart page shows all items with images' },
      { text: 'Quantities can be updated' },
      { text: 'Items can be removed' },
      { text: 'Subtotal, taxes, and total are displayed' },
    ],
    notes: 'Include estimated delivery date',
    taskIds: ['task-21', 'task-22'],
    developmentOrder: 2,
    dependentUserStoryIds: ['story-9'],
    contextualQuestions: [],
  },
  'story-11': {
    id: 'story-11',
    documentId: 'story-11',
    parentFeatureId: 'feature-7',
    title: 'Checkout Flow',
    role: 'shopper',
    action: 'complete the checkout process',
    goal: 'so that I can place my order',
    points: '8',
    acceptanceCriteria: [
      { text: 'Shipping address selection/entry' },
      { text: 'Payment method selection' },
      { text: 'Order review before confirmation' },
      { text: 'Guest checkout option available' },
    ],
    notes: 'Minimize steps for conversion',
    taskIds: ['task-23', 'task-24', 'task-25'],
    developmentOrder: 1,
    dependentUserStoryIds: [],
    contextualQuestions: [],
  },
  'story-12': {
    id: 'story-12',
    documentId: 'story-12',
    parentFeatureId: 'feature-7',
    title: 'Payment Processing',
    role: 'shopper',
    action: 'pay for my order securely',
    goal: 'so that my transaction is completed safely',
    points: '13',
    acceptanceCriteria: [
      { text: 'Credit card form with validation' },
      { text: 'PayPal integration' },
      { text: 'Apple Pay / Google Pay support' },
      { text: 'Payment failure handling' },
    ],
    notes: 'Use Stripe Elements for PCI compliance',
    taskIds: ['task-26', 'task-27', 'task-28'],
    developmentOrder: 2,
    dependentUserStoryIds: ['story-11'],
    contextualQuestions: [],
  },
};

export const ecommerceTasks: Record<string, TaskType> = {
  'task-1': {
    id: 'task-1',
    documentId: 'task-1',
    parentUserStoryId: 'story-1',
    title: 'Create registration form component',
    details: 'Build React component with email, password, confirm password, and terms checkbox fields.',
    priority: 1,
    notes: 'Use react-hook-form for validation',
    dependentTaskIds: [],
    contextualQuestions: [],
  },
  'task-2': {
    id: 'task-2',
    documentId: 'task-2',
    parentUserStoryId: 'story-1',
    title: 'Implement registration API endpoint',
    details: 'Create POST /api/auth/register endpoint with validation and password hashing.',
    priority: 1,
    notes: 'Use bcrypt with salt rounds of 12',
    dependentTaskIds: [],
    contextualQuestions: [],
  },
  'task-3': {
    id: 'task-3',
    documentId: 'task-3',
    parentUserStoryId: 'story-1',
    title: 'Add password strength indicator',
    details: 'Implement visual password strength meter using zxcvbn library.',
    priority: 2,
    notes: 'Show requirements checklist',
    dependentTaskIds: ['task-1'],
    contextualQuestions: [],
  },
  'task-4': {
    id: 'task-4',
    documentId: 'task-4',
    parentUserStoryId: 'story-2',
    title: 'Create email verification service',
    details: 'Implement email service using SendGrid with verification token generation.',
    priority: 1,
    notes: 'Tokens expire after 24 hours',
    dependentTaskIds: [],
    contextualQuestions: [],
  },
  'task-5': {
    id: 'task-5',
    documentId: 'task-5',
    parentUserStoryId: 'story-2',
    title: 'Build verification landing page',
    details: 'Create page that handles verification link clicks and activates accounts.',
    priority: 1,
    notes: 'Handle expired token gracefully',
    dependentTaskIds: ['task-4'],
    contextualQuestions: [],
  },
  'task-6': {
    id: 'task-6',
    documentId: 'task-6',
    parentUserStoryId: 'story-3',
    title: 'Configure Google OAuth',
    details: 'Set up Google Cloud Console project and configure OAuth credentials.',
    priority: 1,
    notes: 'Request only necessary scopes',
    dependentTaskIds: [],
    contextualQuestions: [],
  },
  'task-7': {
    id: 'task-7',
    documentId: 'task-7',
    parentUserStoryId: 'story-3',
    title: 'Implement OAuth callback handler',
    details: 'Create callback endpoint that handles OAuth response and creates/links accounts.',
    priority: 1,
    notes: 'Handle account linking edge cases',
    dependentTaskIds: ['task-6'],
    contextualQuestions: [],
  },
  'task-8': {
    id: 'task-8',
    documentId: 'task-8',
    parentUserStoryId: 'story-4',
    title: 'Build profile edit form',
    details: 'Create editable form for user profile with avatar upload.',
    priority: 1,
    notes: 'Implement image cropping for avatar',
    dependentTaskIds: [],
    contextualQuestions: [],
  },
  'task-9': {
    id: 'task-9',
    documentId: 'task-9',
    parentUserStoryId: 'story-5',
    title: 'Create address management UI',
    details: 'Build address list component with add/edit/delete functionality.',
    priority: 1,
    notes: 'Make default address prominent',
    dependentTaskIds: [],
    contextualQuestions: [],
  },
  'task-10': {
    id: 'task-10',
    documentId: 'task-10',
    parentUserStoryId: 'story-5',
    title: 'Integrate address autocomplete',
    details: 'Add Google Places API for address autocomplete and validation.',
    priority: 2,
    notes: 'Handle international addresses',
    dependentTaskIds: ['task-9'],
    contextualQuestions: [],
  },
  'task-11': {
    id: 'task-11',
    documentId: 'task-11',
    parentUserStoryId: 'story-6',
    title: 'Set up Elasticsearch index',
    details: 'Create product index with appropriate mappings and analyzers.',
    priority: 1,
    notes: 'Include synonyms and stemming',
    dependentTaskIds: [],
    contextualQuestions: [],
  },
  'task-12': {
    id: 'task-12',
    documentId: 'task-12',
    parentUserStoryId: 'story-6',
    title: 'Build search bar component',
    details: 'Create search input with autocomplete dropdown.',
    priority: 1,
    notes: 'Debounce input for performance',
    dependentTaskIds: ['task-11'],
    contextualQuestions: [],
  },
  'task-13': {
    id: 'task-13',
    documentId: 'task-13',
    parentUserStoryId: 'story-6',
    title: 'Implement search API endpoint',
    details: 'Create search endpoint with pagination and relevance scoring.',
    priority: 1,
    notes: 'Log search queries for analytics',
    dependentTaskIds: ['task-11'],
    contextualQuestions: [],
  },
  'task-14': {
    id: 'task-14',
    documentId: 'task-14',
    parentUserStoryId: 'story-7',
    title: 'Build filter sidebar component',
    details: 'Create collapsible filter sidebar with checkbox and range filters.',
    priority: 1,
    notes: 'Make mobile-friendly with bottom sheet',
    dependentTaskIds: [],
    contextualQuestions: [],
  },
  'task-15': {
    id: 'task-15',
    documentId: 'task-15',
    parentUserStoryId: 'story-7',
    title: 'Implement faceted search',
    details: 'Add aggregations to search query for dynamic filter counts.',
    priority: 1,
    notes: 'Cache aggregations for performance',
    dependentTaskIds: ['task-14'],
    contextualQuestions: [],
  },
  'task-16': {
    id: 'task-16',
    documentId: 'task-16',
    parentUserStoryId: 'story-8',
    title: 'Implement user behavior tracking',
    details: 'Track product views, cart additions, and purchases for recommendations.',
    priority: 1,
    notes: 'Respect privacy settings',
    dependentTaskIds: [],
    contextualQuestions: [],
  },
  'task-17': {
    id: 'task-17',
    documentId: 'task-17',
    parentUserStoryId: 'story-8',
    title: 'Build recommendation engine',
    details: 'Create collaborative filtering algorithm based on user behavior.',
    priority: 1,
    notes: 'Start with item-based CF',
    dependentTaskIds: ['task-16'],
    contextualQuestions: [],
  },
  'task-18': {
    id: 'task-18',
    documentId: 'task-18',
    parentUserStoryId: 'story-8',
    title: 'Create recommendation carousel',
    details: 'Build responsive product carousel for displaying recommendations.',
    priority: 2,
    notes: 'Lazy load images',
    dependentTaskIds: ['task-17'],
    contextualQuestions: [],
  },
  'task-19': {
    id: 'task-19',
    documentId: 'task-19',
    parentUserStoryId: 'story-9',
    title: 'Implement add to cart logic',
    details: 'Create cart context with add, remove, and update quantity functions.',
    priority: 1,
    notes: 'Persist to localStorage and sync with server',
    dependentTaskIds: [],
    contextualQuestions: [],
  },
  'task-20': {
    id: 'task-20',
    documentId: 'task-20',
    parentUserStoryId: 'story-9',
    title: 'Build add to cart button',
    details: 'Create reusable button component with quantity selector.',
    priority: 1,
    notes: 'Show loading state during add',
    dependentTaskIds: ['task-19'],
    contextualQuestions: [],
  },
  'task-21': {
    id: 'task-21',
    documentId: 'task-21',
    parentUserStoryId: 'story-10',
    title: 'Create cart page layout',
    details: 'Build cart page with item list, quantity controls, and summary.',
    priority: 1,
    notes: 'Show saved items section',
    dependentTaskIds: [],
    contextualQuestions: [],
  },
  'task-22': {
    id: 'task-22',
    documentId: 'task-22',
    parentUserStoryId: 'story-10',
    title: 'Implement cart calculations',
    details: 'Calculate subtotal, taxes, discounts, and shipping estimates.',
    priority: 1,
    notes: 'Update in real-time',
    dependentTaskIds: ['task-21'],
    contextualQuestions: [],
  },
  'task-23': {
    id: 'task-23',
    documentId: 'task-23',
    parentUserStoryId: 'story-11',
    title: 'Build checkout stepper',
    details: 'Create multi-step checkout flow with progress indicator.',
    priority: 1,
    notes: 'Allow navigation between steps',
    dependentTaskIds: [],
    contextualQuestions: [],
  },
  'task-24': {
    id: 'task-24',
    documentId: 'task-24',
    parentUserStoryId: 'story-11',
    title: 'Implement shipping step',
    details: 'Create shipping address selection with saved addresses and new entry.',
    priority: 1,
    notes: 'Show delivery estimates',
    dependentTaskIds: ['task-23'],
    contextualQuestions: [],
  },
  'task-25': {
    id: 'task-25',
    documentId: 'task-25',
    parentUserStoryId: 'story-11',
    title: 'Build order review step',
    details: 'Create final review page before payment with edit capabilities.',
    priority: 1,
    notes: 'Include promo code entry',
    dependentTaskIds: ['task-24'],
    contextualQuestions: [],
  },
  'task-26': {
    id: 'task-26',
    documentId: 'task-26',
    parentUserStoryId: 'story-12',
    title: 'Integrate Stripe Elements',
    details: 'Set up Stripe Elements for secure card input.',
    priority: 1,
    notes: 'Use PaymentElement for flexibility',
    dependentTaskIds: [],
    contextualQuestions: [],
  },
  'task-27': {
    id: 'task-27',
    documentId: 'task-27',
    parentUserStoryId: 'story-12',
    title: 'Implement PayPal checkout',
    details: 'Add PayPal SDK and express checkout flow.',
    priority: 2,
    notes: 'Support PayPal Credit',
    dependentTaskIds: [],
    contextualQuestions: [],
  },
  'task-28': {
    id: 'task-28',
    documentId: 'task-28',
    parentUserStoryId: 'story-12',
    title: 'Handle payment errors',
    details: 'Implement error handling for declined cards and network issues.',
    priority: 1,
    notes: 'Show retry options',
    dependentTaskIds: ['task-26', 'task-27'],
    contextualQuestions: [],
  },
};

/**
 * Get complete demo SOW state for the E-Commerce Platform
 */
export function getEcommerceDemoState(): SowState {
  return {
    epics: ecommerceEpics,
    features: ecommerceFeatures,
    userStories: ecommerceUserStories,
    tasks: ecommerceTasks,
    contextualQuestions: [
      {
        id: 'q1',
        question: 'What is the primary target market for this e-commerce platform?',
        answer: 'Small to medium businesses selling consumer goods in North America and Europe.',
      },
      {
        id: 'q2',
        question: 'What are the expected transaction volumes?',
        answer: 'Initial target of 10,000 daily transactions scaling to 100,000+ within 2 years.',
      },
      {
        id: 'q3',
        question: 'Are there any specific compliance requirements?',
        answer: 'PCI DSS Level 1 compliance for payment processing, GDPR for EU customers.',
      },
    ],
    globalInformation: demoApps[0].globalInformation,
    selectedModel: 'gpt-4',
    chatApi: 'demo',
    id: 'demo-app-ecommerce',
    apps: {
      'demo-app-ecommerce': demoApps[0],
    },
    isLoading: false,
    error: null,
  };
}

/**
 * Calculate demo metrics
 */
export function calculateDemoMetrics(state: SowState) {
  const epics = Object.values(state.epics);
  const features = Object.values(state.features);
  const userStories = Object.values(state.userStories);
  const tasks = Object.values(state.tasks);

  const totalPoints = userStories.reduce((sum, story) => {
    const points = parseInt(story.points) || 0;
    return sum + points;
  }, 0);

  return {
    totalEpics: epics.length,
    totalFeatures: features.length,
    totalUserStories: userStories.length,
    totalTasks: tasks.length,
    totalPoints,
    completionRate: 87, // Mock completion rate for demo
  };
}
