import {
  Twitter,
  Facebook,
  Instagram,
  Linkedin,
  Github,
  Mail,
  Phone,
  AlertCircle,
  ChevronDown,
  Eye,
  Users,
  Brain,
  BarChart,
  Plug,
  Sparkles,
  Quote,
  Menu,
  Check,
  X,
  ArrowRight,
  Search,
  LoaderCircle,
  type LucideIcon,
  Slack,
  Plus,
  CreditCard,
  Shield,
  Download,
  Gitlab,
  Microchip,
  Link,
  BookOpen,
  Settings,
  Key,
  XIcon,
  ChevronLeft,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  twitter: Twitter,
  facebook: Facebook,
  instagram: Instagram,
  linkedin: Linkedin,
  gitHub: Github,
  mail: Mail,
  phone: Phone,
  alert: AlertCircle,
  chevronDown: ChevronDown,
  eye: Eye,
  users: Users,
  brain: Brain,
  barChart: BarChart,
  plug: Plug,
  sparkles: Sparkles,
  quote: Quote,
  menu: Menu,
  check: Check,
  x: X,
  arrowRight: ArrowRight,
  spinner: LoaderCircle,
  search: Search,
  jira: Download,
  slack: Slack,
  gitLab: Gitlab,
  microsoft: Microchip,
  bitbucket: Microchip,
  plus: Plus,
  creditCard: CreditCard,
  shield: Shield,
  download: Download,
  externalLink: Link,
  openai: BookOpen,
  settings: Settings,
  key: Key,
  xIcon: XIcon,
  chevronLeft: ChevronLeft,
} as const;
