import {
  Twitter,
  Facebook,
  Instagram,
  Linkedin,
  Github,
  Mail,
  Phone,
  AlertCircle,
  ChevronDown,
  Eye,
  Users,
  Brain,
  BarChart,
  Plug,
  Sparkles,
  Quote,
  Menu,
  Check,
  X,
  ArrowRight,
  Search,
  type LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  twitter: Twitter,
  facebook: Facebook,
  instagram: Instagram,
  linkedin: Linkedin,
  gitHub: Github,
  mail: Mail,
  phone: Phone,
  alert: AlertCircle,
  chevronDown: ChevronDown,
  eye: Eye,
  users: Users,
  brain: Brain,
  barChart: BarChart,
  plug: Plug,
  sparkles: Sparkles,
  quote: Quote,
  menu: Menu,
  check: Check,
  x: X,
  arrowRight: ArrowRight,
  search: Search,
} as const;
